// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/scaleway/secrets-store-csi-driver-provider-scw/internal/provider (interfaces: Provider)
//
// Generated by this command:
//
//	mockgen -destination provider_mock.go -package provider . Provider
//

// Package provider is a generated GoMock package.
package provider

import (
	context "context"
	reflect "reflect"

	config "github.com/scaleway/secrets-store-csi-driver-provider-scw/internal/config"
	gomock "go.uber.org/mock/gomock"
	v1alpha1 "sigs.k8s.io/secrets-store-csi-driver/provider/v1alpha1"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// HandleMountRequest mocks base method.
func (m *MockProvider) HandleMountRequest(ctx context.Context, cfg *config.Config) (*v1alpha1.MountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleMountRequest", ctx, cfg)
	ret0, _ := ret[0].(*v1alpha1.MountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleMountRequest indicates an expected call of HandleMountRequest.
func (mr *MockProviderMockRecorder) HandleMountRequest(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMountRequest", reflect.TypeOf((*MockProvider)(nil).HandleMountRequest), ctx, cfg)
}
